### ISSUE TITLE
Delay on notification sound.

### ISSUE THREAD

**Issue by t33st33r** [midnite0/jcatgui9kw#1]
Hello,
I have a slow PC. Once your app open, the first captcha makes no sound. The second captcha makes two sound notifications (second one immediately after the first one). Sometimes one of them sounds clumsy.

Some of the next times, the notification sound is clumsy and delayed.

It happens no matter if I use the embedded notification sound or an external "notify.wav" one.
I think it can be solved if you cache the notification sound to RAM when the app opens and keep it there till it closes, maybe.

PS: Additionally... can you add an option to force language? (I want to force english only) That's not an issue so I am not sure where to post this suggestion.

**Comment by midnite0** [comment]
Hello,
I'm afraid, the caching will not solve the sound problem. Anyway I will do the according changes.
The easiest solution for the language is to start the app with the java user.language parameter.

Change the following line in jCatGUI_9kw.cmd
start javaw.exe -jar jCatGUI_9kw.jar
to 
start javaw.exe -Duser.language=en -jar jCatGUI_9kw.jar

**Comment by midnite0** [comment]
try the new release v1.3
